version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    command: ./boot.sh
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:latest

